import type { ToolDefinition, ToolExecutionContext, ToolBridgeProviderFormat } from "./types";
import { filterToolsForPermission, type FilterToolsForPermissionOptions } from "./permissions";
import { diagnosticTools } from "./tools/diagnostic";
import { editingTools } from "./tools/editing";
import { fileTools } from "./tools/files";
import { gitTools } from "./tools/git";
import { gmailTools } from "./tools/gmail";
import { googleCalendarTools } from "./tools/googleCalendar";
import { mcpTools } from "./tools/mcp";
import { browserTools } from "./tools/browser";
import { mediaTools } from "./tools/media";
import { memoryTools } from "./tools/memory";
import { terminalTools } from "./tools/terminal";
import { webTools } from "./tools/web";

export type ToolRegistryListOptions = FilterToolsForPermissionOptions;

const TOOL_ID_ALIASES: Record<string, string> = {
  apply_patch: "files_apply_patch",
  append_file: "files_append",
  app_preview: "browser_preview_open",
  batch_edit: "files_edit_many",
  batch_read: "files_read_many",
  batch_write: "files_write_many",
  "browser.console": "browser_console_read",
  browser_console: "browser_console_read",
  browser_console_logs: "browser_console_read",
  "browser.open_preview": "browser_preview_open",
  "browser.preview": "browser_preview_open",
  "browser.screenshot": "browser_screenshot_capture",
  "browser.capture_screenshot": "browser_screenshot_capture",
  browser_preview: "browser_preview_open",
  browser_screenshot: "browser_screenshot_capture",
  console_read: "browser_console_read",
  capture_browser_screenshot: "browser_screenshot_capture",
  count_lines: "files_count_lines",
  create_files: "files_write_many",
  copy_file: "files_copy",
  copy_path: "files_copy",
  create_dir: "files_create_directory",
  create_directory: "files_create_directory",
  create_folder: "files_create_directory",
  dir: "files_list",
  edit: "files_exact_replace",
  edit_file: "files_exact_replace",
  edit_files: "files_edit_many",
  editor: "files_exact_replace",
  exact_replace: "files_exact_replace",
  file_editor: "files_exact_replace",
  "files.append": "files_append",
  "files.apply_patch": "files_apply_patch",
  files_applypatch: "files_apply_patch",
  "files.copy": "files_copy",
  "files.edit": "files_exact_replace",
  "files.edit_many": "files_edit_many",
  files_editmany: "files_edit_many",
  files_edit: "files_exact_replace",
  files_exactreplace: "files_exact_replace",
  "files.insert": "files_insert_at_line",
  "files.insert_at_line": "files_insert_at_line",
  "files.move": "files_move",
  "files.create": "files_write_many",
  "files.create_directory": "files_create_directory",
  "files.create_folder": "files_create_directory",
  "files.create_many": "files_write_many",
  "files.mkdir": "files_create_directory",
  files_createdirectory: "files_create_directory",
  files_createfolder: "files_create_directory",
  files_createmany: "files_write_many",
  files_readmany: "files_read_many",
  files_readrange: "files_read_range",
  files_replace: "files_exact_replace",
  "files.replace_range": "files_replace_range",
  "files.replace_span": "files_replace_span",
  files_replacespan: "files_replace_span",
  files_treesummary: "files_tree_summary",
  "files.write": "files_write",
  "files.write_many": "files_write_many",
  files_writemany: "files_write_many",
  file_edit: "files_exact_replace",
  file_editor_tool: "files_exact_replace",
  file_read: "files_read",
  file_stat: "files_stat",
  file_write: "files_write",
  files_grep: "files_search",
  generate_image: "image_generate",
  "files.list": "files_list",
  "files.read": "files_read",
  "files.read_many": "files_read_many",
  "files.read_range": "files_read_range",
  "files.search": "files_search",
  "files.stat": "files_stat",
  "files.tree": "files_tree_summary",
  grep: "files_search",
  "git.branch": "git_branch",
  "git.commit": "git_commit",
  "git.diff": "git_diff",
  "git.init": "git_init",
  "git.pull": "git_pull",
  "git.push": "git_push",
  "git.stage": "git_stage",
  "git.status": "git_status",
  git_branch_create: "git_branch",
  git_create_branch: "git_branch",
  git_repo_status: "git_status",
  git_staged_diff: "git_diff",
  github_branch: "github_create_branch",
  "github.api_delete": "github_api_delete",
  "github.api_read": "github_api_read",
  "github.api_write": "github_api_write",
  "github.branches": "github_list_branches",
  "github.cancel_workflow_run": "github_cancel_workflow_run",
  "github.closed_completed_issues": "github_list_completed_issues",
  "github.close_issue": "github_close_issue",
  "github.comment_issue": "github_comment_issue",
  "github.commit_files": "github_commit_files",
  "github.create_branch": "github_create_branch",
  "github.create_issue": "github_create_issue",
  "github.create_pr": "github_create_pull_request",
  "github.create_release": "github_create_release",
  "github.dispatch_workflow": "github_dispatch_workflow",
  "github.file": "github_read_file",
  "github.get_issue": "github_get_issue",
  "github.get_pr": "github_get_pull_request",
  "github.get_repository": "github_get_repository",
  "github.get_workflow_run": "github_get_workflow_run",
  "github.completed_issues": "github_list_completed_issues",
  "github.issue": "github_get_issue",
  "github.issue_comments": "github_list_issue_comments",
  "github.issue_complete": "github_close_issue",
  "github.issue_done": "github_close_issue",
  "github.issue_duplicate": "github_mark_issue_duplicate",
  "github.issue_reopen": "github_reopen_issue",
  "github.issues": "github_list_issues",
  "github.jobs": "github_list_workflow_run_jobs",
  "github.labels.add": "github_add_issue_labels",
  "github.labels.clear": "github_clear_issue_labels",
  "github.labels.remove": "github_remove_issue_label",
  "github.labels.set": "github_set_issue_labels",
  "github.list_completed_issues": "github_list_completed_issues",
  "github.list_issues": "github_list_issues",
  "github.list_prs": "github_list_pull_requests",
  "github.list_pull_requests": "github_list_pull_requests",
  "github.list_repositories": "github_list_repositories",
  "github.list_tags": "github_list_tags",
  "github.mark_issue_duplicate": "github_mark_issue_duplicate",
  "github.merge_pr": "github_merge_pull_request",
  "github.merge_pull_request": "github_merge_pull_request",
  "github.milestones": "github_list_milestones",
  "github.notifications": "github_list_notifications",
  "github.pr_files": "github_list_pull_request_files",
  "github.pr_commits": "github_list_pull_request_commits",
  "github.pr_reviewers": "github_request_pull_request_reviewers",
  "github.pr_reviews": "github_list_pull_request_reviews",
  "github.pr": "github_create_pull_request",
  "github.prs": "github_list_pull_requests",
  "github.read_file": "github_read_file",
  "github.reopen_issue": "github_reopen_issue",
  "github.release_notes": "github_generate_release_notes",
  "github.releases": "github_list_releases",
  "github.repo": "github_get_repository",
  "github.repos": "github_list_repositories",
  "github.rerun_workflow_run": "github_rerun_workflow_run",
  "github.search_issues": "github_search_issues",
  "github.search_repositories": "github_search_repositories",
  "github.search_users": "github_search_users",
  "github.security": "github_list_code_scanning_alerts",
  "github.search": "github_search_code",
  "github.semantic_search": "github_semantic_search",
  "github.star": "github_star_repository",
  "github.tags": "github_list_tags",
  "github.tree": "github_list_tree",
  "github.update_issue": "github_update_issue",
  "github.update_pr": "github_update_pull_request",
  "github.update_pull_request": "github_update_pull_request",
  "github.workflow_runs": "github_list_workflow_runs",
  "github.workflows": "github_list_workflows",
  github_api_delete: "github_api_delete",
  github_api_read: "github_api_read",
  github_api_write: "github_api_write",
  github_close_issue: "github_close_issue",
  github_complete_issue: "github_close_issue",
  github_completed_issues: "github_list_completed_issues",
  github_issue_comments: "github_list_issue_comments",
  github_issue: "github_get_issue",
  github_issues: "github_list_issues",
  github_mark_issue_duplicate: "github_mark_issue_duplicate",
  github_reopen_issue: "github_reopen_issue",
  github_pull_requests: "github_list_pull_requests",
  github_repositories: "github_list_repositories",
  github_repos: "github_list_repositories",
  github_search_issues: "github_search_issues",
  github_search_repositories: "github_search_repositories",
  github_search_users: "github_search_users",
  github_semantic: "github_semantic_search",
  github_star: "github_star_repository",
  github_tags: "github_list_tags",
  github_workflow_dispatch: "github_dispatch_workflow",
  email_account: "gmail_account",
  email_api_delete: "gmail_api_delete",
  email_api_read: "gmail_api_read",
  email_api_write: "gmail_api_write",
  email_create_draft: "gmail_create_draft",
  email_delete_draft: "gmail_delete_draft",
  email_get_message: "gmail_get_message",
  email_get_thread: "gmail_get_thread",
  email_labels: "gmail_list_labels",
  email_list_labels: "gmail_list_labels",
  email_search: "gmail_search_messages",
  email_search_messages: "gmail_search_messages",
  email_send_draft: "gmail_send_draft",
  email_send_message: "gmail_send_message",
  email_trash: "gmail_trash_message",
  email_untrash: "gmail_untrash_message",
  "gmail.account": "gmail_account",
  "gmail.api_delete": "gmail_api_delete",
  "gmail.api_read": "gmail_api_read",
  "gmail.api_write": "gmail_api_write",
  "gmail.create_draft": "gmail_create_draft",
  "gmail.create_label": "gmail_create_label",
  "gmail.delete_draft": "gmail_delete_draft",
  "gmail.get_message": "gmail_get_message",
  "gmail.get_thread": "gmail_get_thread",
  "gmail.labels": "gmail_list_labels",
  "gmail.list_labels": "gmail_list_labels",
  "gmail.modify_labels": "gmail_modify_message_labels",
  "gmail.search": "gmail_search_messages",
  "gmail.search_messages": "gmail_search_messages",
  "gmail.send_draft": "gmail_send_draft",
  "gmail.send_message": "gmail_send_message",
  "gmail.send_separate": "gmail_send_separate_messages",
  "gmail.trash": "gmail_trash_message",
  "gmail.untrash": "gmail_untrash_message",
  gmail_direct_send: "gmail_send_message",
  gmail_full_api_delete: "gmail_api_delete",
  gmail_full_api_read: "gmail_api_read",
  gmail_full_api_write: "gmail_api_write",
  gmail_send: "gmail_send_message",
  calendar_account_status: "calendar_account",
  calendar_api_delete: "calendar_api_delete",
  calendar_api_read: "calendar_api_read",
  calendar_api_write: "calendar_api_write",
  calendar_availability: "calendar_free_busy",
  calendar_calendars: "calendar_list_calendars",
  calendar_clear_completed_tasks: "calendar_clear_completed_tasks",
  calendar_create: "calendar_create_event",
  calendar_create_calendar: "calendar_create_calendar",
  calendar_create_task: "calendar_create_task",
  calendar_create_task_list: "calendar_create_task_list",
  calendar_delete: "calendar_delete_event",
  calendar_delete_calendar: "calendar_delete_calendar",
  calendar_delete_task: "calendar_delete_task",
  calendar_delete_task_list: "calendar_delete_task_list",
  calendar_event: "calendar_get_event",
  calendar_events: "calendar_search_events",
  calendar_freebusy: "calendar_free_busy",
  calendar_get_task: "calendar_get_task",
  calendar_list: "calendar_list_calendars",
  calendar_list_task_lists: "calendar_list_task_lists",
  calendar_list_tasks: "calendar_list_tasks",
  calendar_move_task: "calendar_move_task",
  calendar_read_event: "calendar_get_event",
  calendar_search: "calendar_search_events",
  calendar_task: "calendar_get_task",
  calendar_task_lists: "calendar_list_task_lists",
  calendar_tasks: "calendar_list_tasks",
  calendar_update: "calendar_update_event",
  calendar_update_calendar: "calendar_update_calendar",
  calendar_update_task: "calendar_update_task",
  calendar_update_task_list: "calendar_update_task_list",
  "calendar.account": "calendar_account",
  "calendar.api_delete": "calendar_api_delete",
  "calendar.api_read": "calendar_api_read",
  "calendar.api_write": "calendar_api_write",
  "calendar.clear_completed_tasks": "calendar_clear_completed_tasks",
  "calendar.create_event": "calendar_create_event",
  "calendar.create_calendar": "calendar_create_calendar",
  "calendar.create_task": "calendar_create_task",
  "calendar.create_task_list": "calendar_create_task_list",
  "calendar.delete_event": "calendar_delete_event",
  "calendar.delete_calendar": "calendar_delete_calendar",
  "calendar.delete_task": "calendar_delete_task",
  "calendar.delete_task_list": "calendar_delete_task_list",
  "calendar.free_busy": "calendar_free_busy",
  "calendar.get_event": "calendar_get_event",
  "calendar.get_task": "calendar_get_task",
  "calendar.list_calendars": "calendar_list_calendars",
  "calendar.list_task_lists": "calendar_list_task_lists",
  "calendar.list_tasks": "calendar_list_tasks",
  "calendar.move_task": "calendar_move_task",
  "calendar.search_events": "calendar_search_events",
  "calendar.update_event": "calendar_update_event",
  "calendar.update_calendar": "calendar_update_calendar",
  "calendar.update_task": "calendar_update_task",
  "calendar.update_task_list": "calendar_update_task_list",
  "google_calendar.account": "calendar_account",
  "google_calendar.api_delete": "calendar_api_delete",
  "google_calendar.api_read": "calendar_api_read",
  "google_calendar.api_write": "calendar_api_write",
  "google_calendar.clear_completed_tasks": "calendar_clear_completed_tasks",
  "google_calendar.create_calendar": "calendar_create_calendar",
  "google_calendar.create_event": "calendar_create_event",
  "google_calendar.create_task": "calendar_create_task",
  "google_calendar.create_task_list": "calendar_create_task_list",
  "google_calendar.delete_calendar": "calendar_delete_calendar",
  "google_calendar.delete_event": "calendar_delete_event",
  "google_calendar.delete_task": "calendar_delete_task",
  "google_calendar.delete_task_list": "calendar_delete_task_list",
  "google_calendar.free_busy": "calendar_free_busy",
  "google_calendar.get_event": "calendar_get_event",
  "google_calendar.get_task": "calendar_get_task",
  "google_calendar.list_calendars": "calendar_list_calendars",
  "google_calendar.list_task_lists": "calendar_list_task_lists",
  "google_calendar.list_tasks": "calendar_list_tasks",
  "google_calendar.move_task": "calendar_move_task",
  "google_calendar.search_events": "calendar_search_events",
  "google_calendar.update_event": "calendar_update_event",
  "google_calendar.update_calendar": "calendar_update_calendar",
  "google_calendar.update_task": "calendar_update_task",
  "google_calendar.update_task_list": "calendar_update_task_list",
  google_task: "calendar_get_task",
  google_task_lists: "calendar_list_task_lists",
  google_tasks: "calendar_list_tasks",
  google_tasks_create: "calendar_create_task",
  "image.generate": "image_generate",
  "image.generation": "image_generate",
  image_generation: "image_generate",
  image_generate_9router: "image_generate",
  images_generate: "image_generate",
  insert_at_line: "files_insert_at_line",
  line_count: "files_count_lines",
  list: "files_list",
  list_dir: "files_list",
  list_directory: "files_list",
  ls: "files_list",
  memory: "memory_search",
  "memory.search": "memory_search",
  "memory-search": "memory_search",
  memory_recall: "memory_search",
  "mcp.call_tool": "mcp_call_tool",
  "mcp.list_servers": "mcp_list_servers",
  "mcp.list_tools": "mcp_list_tools",
  mcp_call: "mcp_call_tool",
  mcp_call_tool: "mcp_call_tool",
  mcp_servers: "mcp_list_servers",
  mcp_tools: "mcp_list_tools",
  project_memory: "memory_search",
  recall_memory: "memory_search",
  move_file: "files_move",
  move_path: "files_move",
  mkdir: "files_create_directory",
  open_browser_preview: "browser_preview_open",
  patch_apply: "files_apply_patch",
  preview_app: "browser_preview_open",
  preview_url: "browser_preview_open",
  read: "files_read",
  read_browser_console: "browser_console_read",
  read_file: "files_read",
  read_range: "files_read_range",
  read_files: "files_read_many",
  read_many: "files_read_many",
  read_range_file: "files_read_range",
  replace_range: "files_replace_range",
  replace_span: "files_replace_span",
  span_replace: "files_replace_span",
  search: "files_search",
  search_files: "files_search",
  search_memory: "memory_search",
  shell_command: "terminal_run",
  dev_server_status: "terminal_dev_server_status",
  read_terminal_session: "terminal_read_session",
  run_command: "terminal_run",
  stat: "files_stat",
  terminal: "terminal_run",
  terminal_command: "terminal_run",
  terminal_dev_server: "terminal_dev_server_status",
  terminal_dev_server_status: "terminal_dev_server_status",
  terminal_exec: "terminal_run",
  terminal_list: "terminal_list_sessions",
  terminal_list_sessions: "terminal_list_sessions",
  terminal_read: "terminal_read_session",
  terminal_read_session: "terminal_read_session",
  "terminal.run": "terminal_run",
  "terminal.run_command": "terminal_run",
  terminal_run_command: "terminal_run",
  terminal_sessions: "terminal_list_sessions",
  tree: "files_tree_summary",
  tree_summary: "files_tree_summary",
  write_files: "files_write_many",
  write_many: "files_write_many",
  run_terminal: "terminal_run",
  brave_search: "web_search",
  "brave.search": "web_search",
  "brave-search": "web_search",
  duckduckgo_search: "web_search",
  "duckduckgo.search": "web_search",
  "duckduckgo-search": "web_search",
  search_web: "web_search",
  screenshot_browser: "browser_screenshot_capture",
  take_screenshot: "browser_screenshot_capture",
  "search.web": "web_search",
  "search-web": "web_search",
  web: "web_search",
  "web.search": "web_search",
  "web-search": "web_search",
  write_file: "files_write",
};

export class ToolRegistry {
  private readonly tools = new Map<string, ToolDefinition>();

  constructor(initialTools: ToolDefinition[] = []) {
    initialTools.forEach((tool) => this.register(tool));
  }

  get(id: string) {
    return this.tools.get(this.resolveId(id));
  }

  list() {
    return [...this.tools.values()];
  }

  listForContext(
    context: Pick<ToolExecutionContext, "permissionMode">,
    providerFormat?: ToolBridgeProviderFormat,
    options?: ToolRegistryListOptions,
  ) {
    return filterToolsForPermission(this.list(), context, options).filter((tool) =>
      isToolCompatibleWithProvider(tool, providerFormat),
    );
  }

  register(tool: ToolDefinition) {
    if (this.tools.has(tool.id)) {
      throw new Error(`Tool bridge registry already has a tool named ${tool.id}.`);
    }

    this.tools.set(tool.id, tool);
  }

  resolveId(id: string) {
    const normalizedId = id.trim();
    return TOOL_ID_ALIASES[normalizedId.toLowerCase()] ?? normalizedId;
  }
}

export function createDefaultToolRegistry() {
  return new ToolRegistry([
    ...diagnosticTools,
    ...fileTools,
    ...editingTools,
    ...terminalTools,
    ...browserTools,
    ...gitTools,
    ...gmailTools,
    ...googleCalendarTools,
    ...webTools,
    ...mediaTools,
    ...memoryTools,
    ...mcpTools,
  ]);
}

export function isToolCompatibleWithProvider(tool: ToolDefinition, providerFormat: ToolBridgeProviderFormat | undefined) {
  return !providerFormat || !tool.compatibleProviders || tool.compatibleProviders.includes(providerFormat);
}
